name: Update Artists Index
on:
  repository_dispatch:
    types: [new-artist-submission]

jobs:
  update-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Update JSON file
        env:
          SUBMISSION_DATA: ${{ toJson(github.event.client_payload) }}
        run: |
          python update_index.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add artists.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Add new artist submission"
          git push
